create database customer;
use customer;
select * from customer_shopping_data;

rename table customer_shopping_data to customers;

select * from customers limit 10;

-- Q1. What is the total revenue generated by male vs. female customers?

select gender, sum(purchase_amount) as Revenue from customers group by gender;

-- Q2. Which customers used a discount but still spent more than the average purchase amount?

 select customer_id, purchase_amount from customers
 where discount_applied = 'Yes' and purchase_amount >=all (select avg(purchase_amount)
 from customers);
 
 -- Q3. Which are the top 5 products with the highest average review rating?
 
 select item_purchased, round(avg(review_rating),2) as 'Average review rating' 
 from customers group by 
 item_purchased order by avg(review_rating) desc limit 5;
 
 ## products with higher average rating can be sold at a premium price
 ## and can also be marketed more since it's selling more
 
 -- Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 
 
 select distinct shipping_type from customers;
 
 select shipping_type, avg(purchase_amount) from customers where 
 shipping_type in ('Standard', 'Express') group by shipping_type;
 
 # this is done to know which type of shipping is faster and
 # to focus on that more
 
-- Q5. Do subscribed customers spend more? Compare average spend and total revenue 
-- between subscribers and non-subscribers.
select * from customers limit 10;

select subscription_status, count(customer_id) as total_customers,
round(avg(purchase_amount),2) as avg_spend, 
round(sum(purchase_amount),2) as total_revenue
from customers group by subscription_status order by 
total_revenue, avg_spend desc;

# we do this to check the common business problem of checking if who 
# spends more the subscribers or non-subscribers. We can see the non subscribers
# spending more money here. 

-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?
select * from customers limit 10;

#calculate discount rate per product, which product relies heavily on discount to sell

SELECT discount_applied, COUNT(*) AS count
FROM customers
GROUP BY discount_applied; -- checking how many yes and no is there

select item_purchased, 
round( 100 * sum(case when discount_Applied = 'Yes' then 1 else 0 end)/count(*),2)
as discount_rate
from customers group by item_purchased 
order by discount_rate desc limit 5;
-- here it says that the items were sold 10 times but 5 times with discount

-- Q7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment. 
select * from customers limit 10;

# lets say if a customer has bought 1 time he is new
# 2-10 times he's returning
# 10 plus times - he's loyal

with customer_type as(
select customer_id, previous_purchases, 
case when previous_purchases = 1 then 'New'
when previous_purchases between 2 and 10 then 'Returning'
else 'Loyal'
end as customer_segment
from customers)
select customer_segment, count(*) as "Number of customers"
from customer_type group by customer_segment;
# this is cte

-- Q8. What are the top 3 most purchased products within each category? 
select * from customers limit 10;

WITH item_counts AS (
    SELECT category,
           item_purchased,
           COUNT(customer_id) AS total_orders,
           ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
    FROM customers
    GROUP BY category, item_purchased
)
SELECT item_rank,category, item_purchased, total_orders
FROM item_counts
WHERE item_rank <=3;

# top 3 items within each category are the best sellers

-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also 
-- likely to subscribe?
select * from customers limit 10;
# if repeat buyers are subscribers it's great for the business
# and if loyal customers are not subscribing which means they are not attracted
# to the subscription offers that much 

select subscription_status, count(customer_id) as repeat_buyers
from customers where previous_purchases >5 group by subscription_status;

-- Q10. What is the revenue contribution of each age group? 
select * from customers limit 10;

select age_group, sum(purchase_amount) as revenue_contribution
from customers group by age_group ORDER BY revenue_contribution desc;

# young adults are giving the most revenue here
